### ISSUE TITLE
为何不用图标名称访问呢

### ISSUE THREAD

**Issue by hqlulu** [JohnWong/IconFont#1]
接口设计有点反人类啊，设计图标是有名字的，为啥用这些字符
# define kTBCityIconCheck TBCityIconInfoMake(@"\U0000e601", 24, [UIColor blackColor])

设计成这样多好呢：
# define kTBCityIconCheck TBCityIconInfoMake(@"check", 24, [UIColor blackColor])

从check映射到\U0000e601可以做一个字体关系映射表啊
自动生成一个映射关系，粘贴到代码里也许就可以了，接口内部很容易处理

NSDictonary \* xxx = @{
@"check":@"\U0000e601",
etc..
}

**Comment by JohnWong** [comment]
是的。我也曾经这样考虑过，develop分支想做这样的事情。想法是在xcode运行时增加脚本（或者手动运行）来读取映射关系写入到代码文件中，不过并没有开发完成。因为工作内容的变化，后面没有用到这个库了。如果你有精力来改进，欢迎提PR。
