### ISSUE TITLE
Icon底部被截断

### ISSUE THREAD

**Issue by wonderffee** [JohnWong/IconFont#6]
遇到有Icon内部撑得比较满，换言之四周的空白间距非常小的情况下，可以很明显地看到图片底部被截断了一点了，在你的代码基础上做了一个Demo，你可以看看：https://github.com/wonderffee/IconFont

在这个Demo里我只显示了一个Icon，这个Icon的底部应该是一个完整的圆弧形，但是实际上显示是不完整的。怀疑UIGraphicsBeginImageContext绘图有Bug还是怎么的

**Comment by JohnWong** [comment]
<img width="478" alt="screen shot 2017-05-02 at 18 12 16" src="https://cloud.githubusercontent.com/assets/2053617/25614118/3ce97ee4-2f63-11e7-887c-a17f38357b54.png">

用字体工具FontForge来看，确实是一部分图形超出了字体正常区域。
